ethereum/pyethereum

- pyethereum/tester.py
- tests/test_contracts.py
> tester.abi_contract always calls last function

- pyethereum/tester.py
Updated the profile method of the state class in the tester submodule to use the new abi stuff, like the call method of the same class.
> updated profile to use new call syntax

- pyethereum/tester.py
I made a couple mistakes last pull request and this fixed those! :p
> Fixed mistakes in last commit

- tests/test_contracts.py
> test for ecrecover

- ethereum/opcodes.py
Sources: http://gavwood.com/Paper.pdf and https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L1940 .
> Update "outs" counts for RETURN and SUICIDE opcodes

- ethereum/abi.py
> Implement `bool` return type support.

- ethereum/abi.py
- ethereum/blocks.py
- ethereum/opcodes.py
- ethereum/vm.py
minor change for python 3 compatible string formatting
> update strings formatting to be python3 friendly

- ethereum/slogging.py
- ethereum/tests/test_logging.py
remove structlog from logging of ethereum
> remove structlog from logging of ethereum

- ethereum/slogging.py
- ethereum/tests/test_logging.py
Correct count created handlers
> Correct count created handlers

- ethereum/tests/test_chain.py
- ethereum/testutils.py
- ethereum/transactions.py
This fixes all but the following tests:
- Two block tests (https://github.com/ethereum/tests/tree/develop/BlockchainTests/RandomTests) which look weird to me (genesis receipts root is not empty trie root)
- Two genesis tests (related to https://github.com/ethereum/pyethapp/issues/47)
Please review before merging, especially this line: https://github.com/ethereum/pyethereum/blob/test_fixes/ethereum/transactions.py#L63
> Test fixes

- ethereum/_solidity.py
this issue was observed, debugged, fixed, and tested by running truffle and eth-testrpc
> fixes for Solidity 0.1.2 changes

- ethereum/specials.py
- ethereum/tests/test_contracts.py
- ethereum/transactions.py
Fix differences in naming:
vbuterin/pybitcointools | czepluch/pysecp256k1 
--- | ---
`def ecdsa_raw_recover(msghash, vrs):` | `def ecdsa_recover_raw(rawhash, vrs):`
`def ecdsa_raw_sign(msghash, priv):` | `def ecdsa_sign_raw(rawhash, key):`
> Fixed naming differences between the c_secp256k1 and bitcoin libraries

- ethereum/specials.py
- ethereum/transactions.py
- requirements.txt
- setup.cfg
- setup.py
Remove bitcointools fallback and use consolidated secp256k1 library
Fixes: #313
> Switch to secp256k1

- .travis.yml
- dev_requirements.txt
- ethereum/slogging.py
- ethereum/tester.py
- ethereum/tests/conftest.py
- ethereum/tests/test_abi.py
- ethereum/tests/test_blocks.py
- ethereum/tests/test_chain.py
- ethereum/tests/test_contracts.py
- ethereum/tests/test_genesis.py
- ethereum/tests/test_keys.py
- ethereum/tests/test_logging.py
- ethereum/tests/test_remoteblocks.py
- ethereum/tests/test_state.py
- ethereum/tests/test_transactions.py
- ethereum/tests/test_trie.py
- ethereum/tests/test_trie_next_prev.py
- ethereum/tests/test_vm.py
- ethereum/tests/test_vm_failing.py
- ethereum/testutils.py
Reduce code duplication and generate tests using pytest's `pytest_generate_tests`
> Cleanup test loading

- ethereum/guardian.py
The path to the serpent source file was wrong in `ethereum/guardian.py`
Added the appropriate prefix to the path
Also includes two whitespace fixes that my editor did automatically
> Minor fixes for serenity code

- ethereum/abi.py
- ethereum/blocks.py
- ethereum/tester.py
- ethereum/tests/test_contracts.py
- ethereum/tests/test_solidity.py
- ethereum/transactions.py
abi.py:
- reodering of the functions
- added some documentation
- refactored the ContractTranslator
- Simplified it __init__
- Do not ignore the constructor description
- Added encoding for the constructor parameters
tester.py:
- fixed pylint complaints
- pep8
- added path and the contract costructor parametes into `contract` and
`abi_contract`
blocks.py, transactions.py, test_contracts.py:
- comestic changes and small fixes
> Added constructor arguments and path in tester

- ethereum/_solidity.py
- ethereum/tests/contracts/contract_names.sol
- ethereum/tests/contracts/seven_contract.sol
- ethereum/tests/contracts/seven_contract_without_import.sol
- ethereum/tests/contracts/seven_library.sol
- ethereum/tests/test_solidity.py
Added functions to handle libraries symbols and dependency compilation.
> solc rewrite

- ethereum/blocks.py
- ethereum/config.py
- setup.cfg
- setup.py
This supersedes #382 after #373 was finished.
> Possible DAO HF impl for reference

- ethereum/blocks.py
- ethereum/child_dao_list.py
- ethereum/config.py
- ethereum/tests/test_blocks.py
This implements the DAO hf as it was committed onto the `state_revamp` branch. This branches out from the 1.4.0 release and will revert the changes from the pulled 1.5.0 release.
> Dao hf release

- ethereum/blocks.py
> close #395

- .travis.yml
- ethereum/_solidity.py
- ethereum/tests/test_solidity.py
- ethereum/tests/test_tester.py
Fork of #432 -- rebased on latest `develop`
> Fix solidity combinedjson

- ethereum/state_transition.py
This PR fixes some bytes incompatibilities with Python3
> Fix state_transition.py Python3 incompatibility

- ethereum/transaction_queue.py
> Fix TransactionQueue.diff()

- ethereum/transaction_queue.py
> Fix TransactionQueue's non-stable sorting

- ethereum/utils.py
Fixes ImportError in the except block. The error was:
`ImportError: No module named warning`
> Update utils.py, fix ImportError

- ethereum/tools/tester.py
make_head_candidate() returns a tuple
> tester.Chain.mine() fix

- ethereum/new_state.py
> Add a is_SERENITY() method to new_state.State

- .travis.yml
- Makefile
- ethereum/tests/test_genesis.py
- ethereum/tests/test_serialization.py
- ethereum/tests/test_tester.py
- ethereum/tests/test_transactions.py
- ethereum/tests/test_trie.py
- ethereum/tests/todo/test_vm.py
Also create a new Makefile rule (test-failing) which runs the tests that are currently failing
> Fix ImportErrors in a bunch of tests and add them to the list we run on travis

- README.md
- README.rst
I've added a link of LICENSE file to LICENSE title to could see the LICENSE right away.
> Link the LICENSE title to LICENSE file

- ethereum/slogging.py
- ethereum/snapshot.py
- ethereum/vm.py
For trace equivalence testing, this fixes the trace to follow the work-in-progress standard https://github.com/ethereum/tests/issues/249
> standardized tracing
