ethereum/pyethereum

pyethereum/slogging.py
I needed to change  _nameToLevel => _NAME_TO_LEVEL in slogging.py to run against the current github version of structlog.
This was a very naive modification -- I'm not much of a Python programmer, and I wonder whether the inverse map in structlog/stdlib.py, _LEVEL_TO_NAME might need to be updated in sync. But this was enough to my attempts to play around with Trie.py to work.
=> Updated slogging.py to track changed name in structlog 

requirements.txt
`yaml` is used in the code without being installed.
=> Add missing dependency (PyYAML) to requirements.txt

ethereum/_solidity.py, ethereum/tests/test_solidity.py
`solidity.compile_rich()` is used by pyethapp's `eth_compileSolidity` JSON-RPC method. 
This commit updates it's output to be on-par with geth's.
Includes tests.
Fixes: ethereum/pyethapp#30
=> Update `_solidity.compile_rich()` output to mirror geth

dev_requirements.txt, ethereum/slogging.py, ethereum/tests/conftest.py, ethereum/tests/test_logging.py, ethereum/tests/test_solidity.py, ethereum/utils.py
Refactor `slogging` to fix several issues
- Improve overall readability
- Enable logging re-configuration without side-effects
- Stop bound loggers "contaminating" their parents
- Add support to highlight log messages to ease debugging during development
=> Refactor logging

dev_requirements.txt, ethereum/ethash_utils.py, ethereum/keys.py, ethereum/utils.py, requirements.txt
pycryptodome works for both py27 and pypy and supports keccak
Use pycryptodome for sha3_256 hashing
Use version 3.3.1 or higher of pycryptodome
Force version 0.5 of pytest-timout, since newer versions seem to break coverage thus not allowing travis to run the test suite.
=> exclusively use pycryptodome for sha3_256 hashing 

ethereum/abi.py
I think `noprint` should default to `True` in the `listen` method of the contract translator ABI for the following reasons:
* Why print the return value inside the method and provide an option to turn it off, when a developer can easily use `print(ct.listen(log))` to print the return value to provide the same functionality?
* It doesn't make any sense for API methods to print results as well as return them. API methods should provide an interface for programmers to deal with results, with the programmer deciding how that result is returned to the user, not the API.
* It's not consistent with other API methods. This is the only method where you must pass `noprint=True` to it in order to preventing it to from printing the console.
* It provides a headache for developers creating console …
=> API calls should not print results

ethereum/abi.py, ethereum/tests/test_abi.py, ethereum/tests/test_contracts.py
`abi.decint` is used to decode BOTH signed and unsigned integers.
* it make the bound check hard to understand, because it mixes int's lower bound and uint's upper bound:
`if is_numeric(n) and n < 2**256 and n >= -2**255:`
* If the input is bytes it will always decode those bytes to **unsigned** int, cause inconsistent semantic - if input is int/uint, the output is int/uint; if input is bytes of int/uint, the output is uint.
Add a new argument `signed`, default to `False`, behave accordingly.
With signed int's bound check fix, `test_ecrecover` breaks because the types of its arguments default to `int256`. Declare them to `uint256`.
```
$ cat test_ecrecover.se
def test_ecrecover(h, v, r, s):
return(ecrecover(h, v, r, s))
$ serpent mk_signature test_ecrecover.se
extern test_ecrecover.se: …
```
=> Fix abi.decint

ethereum/chain.py
Hi,
While I was debugging https://github.com/ethereum/pyethapp/pull/123 I noticed that I'd sometimes 
not get back a True value for `success` https://github.com/ethereum/pyethapp/blob/develop/pyethapp/eth_service.py#L220 when I was running `add_transaction`.  
It looked like things were being added OK in the end so I dug a little deeper and it seemed to be coming from https://github.com/ethereum/pyethereum/blob/develop/ethereum/chain.py#L367  
I was running `pyethapp` and then entered the console mode to use `%debug` to set a few break points and step through code.  I probably sat too long reviewing some parts of the code and things changed so I ended up going down the `head_candidate changed during validation` path more than folks typically would during normal operations.   Since other …
=> pyethapp's on_new_head_candidate callbacks are not called when head_candidate changed during validation

.travis.yml, ethereum/_solidity.py, ethereum/tests/test_solidity.py
This adds the ability to compile `.sol` files by `path` instead of a `code` string with `solc_wrapper`.
Now it is possible to make full use of the `import` statement of solidity.
Note: libraries still need to be deployed ahead of time and provided through the `libraries={...}` kwarg. But now you can use the same source file for deployment and reference in the `import`.
=> Solidity compile from file

ethereum/blocks.py
`lazy_encode` is meant to prevent encoding operations unless needed in trace-logging. In trace logging, binary values should be hex encoded.
This commit adds a more involved approach to reformat/encode the `changes`-logging entries, that considers different kinds of input formats. It considers these three cases:
- an entry with three items: a name, a hex address and a value
- an entry with three items: with the name `code`, a hex address and a hex value
- an entry with four items: a name and three hex encoded items 
This should fix #352.
=> Failsafe lazy encode

ethereum/tester.py, ethereum/tests/contracts/simple_contract.sol, ethereum/tests/test_tester.py
The change to support constructor arguments in `tester.py` extracted `ContractTranslator` from `ABIContract` to `state.abi_contract` breaking the api. This fix adds back the support for a string containing the json abi.
=> Fix for the issue #370

ethereum/abi.py, ethereum/tester.py, ethereum/tests/test_abi.py, ethereum/tests/test_contracts.py, ethereum/utils.py
- changed the type real to fixed
- expanded the types handled by the _canonical_type function
- added extensive tests for int/uint types
- added tests for function selectors
- added logic to parse logs that don't depends on a processblock.Log
instance
- added documentation for the encode_single function
- added function to zero pad to the right
breaking changes:
- `decint` raises if value is a string and out-of-bounds
- `encode_single`:
- `int` and `uint` raises ValueOutOfBounds instead of EncodingError
- `string` raises if the supplied value is not a valid utf8
- `int`, `uint`, `fixed`, and `ufixed` raises if the type `sub` is
invalid
- renamed type `real` to `fixed`
=> event parsing, tests, real -> fixed

ethereum/utils.py
the `cool_checksum` feature was not python 3 compatible. 
It is not in the critical path, so I added an `isinstance` check for handling the py3 case.
=> Py3 cool checksum

ethereum/_solidity.py
Via the use of the `SOLC_BINARY` environment variable the user can now
set a specific path to his solc executable if for example said user is
compiling solidity from source.
=> Allow setting of a specific solc binary

ethereum/_solidity.py, ethereum/tests/test_solidity.py
Since `compile()` has a `**kwargs` at the end we can easily add an
optional `extra_args` argument to all the compiler calls.
We for example need this if we would like to specify specific locations
on the system path where contracts can be imported from.
=> Add extra args to solc

ethereum/abi.py, ethereum/blocks.py, ethereum/chain.py, ethereum/ethash_utils.py, ethereum/fastvm.py, ethereum/keys.py, ethereum/processblock.py, ethereum/pruning_trie.py, ethereum/tests/profile_vm.py, ethereum/tests/test_blocks.py, ethereum/tests/test_bloom.py, ethereum/tests/test_chain.py, ethereum/tests/test_genesis.py, ethereum/tests/test_solidity.py, ethereum/tests/test_transactions.py, ethereum/tests/test_trie.py, ethereum/testutils.py, ethereum/transactions.py, ethereum/trie.py, ethereum/utils.py, ethereum/vm.py
Fixes #421 
In pyrlp 0.4.7 encode_hex was changed to return a normal string instead
of a byte string. In python3 the pyethereum code expects encode_hex to
return a byte string so this was a breaking change.
This commit fixes it by checking the version of pyrlp by checking
encode_hex's return type, and if it's not a byte string wraps encode_hex
with a function that will encode the string into a byte string.
NOTE: I think it may actually be better to update all the codebase to support rlp 0.4.7, and change the wrapper to instead support older versions, but this requires more understanding of this internals of the project than i currently have and I think this provides a suitable solution to this in the mean time.
=> Wrap encode_hex to support changes to pyrlp 0.4.7

.travis.yml, .travis/install_solc.sh
This is an alternative to #437 without the problem of a 3rd party release repository.
The method is borrowed from `py-solc` -- thanks @pipermerriam!
=> Install solc from zip

ethereum/blocks.py, ethereum/tests/test_chain.py, ethereum/utils.py
Maximum allowed value in EVM is `2 ** 256 - 1`
- `ethereum/utils.py::denoms.turing` was `2 ** 256` before
- `ethereum/blocks.py` didn't restrict balances/values to be below `2 ** 256` before
=> Shouldn't have a number equal to 2^256 in EVM

ethereum/_solidity.py, ethereum/tests/test_solidity.py
When solc is not installed, compile_code() would end up using None as the first element in the args list passed to subprocess.Popen(), causing it to crash with an AttributeError. This fixes that
=> compile_code: raise exception when solc missing

.travis/install_solc.sh
When using a cached solidity, we still need to install the OS-dependencies.
=> Always install solidity dependencies

ethereum/utils.py, requirements.txt
`pysha3` adjusted `sha3_256` to the newer standard. Since we rely on the `keccac`
version, we will now explicitely use `keccak_256` from `pysha3>=1.0.1`.
See: https://github.com/tiran/pysha3/blob/3b31ed7beaed82d1c5300621ad53b51a0fa3bf18/CHANGES.txt#L4-L11
=> Adjust to pysha3 breaking changes

ethereum/blocks.py
Set the genesis block to the given timestamp (e.g. in a pyethapp [custom genesis](https://github.com/ethereum/pyethapp/wiki/Custom-genesis)). Needs the correct timestamp to get the right genesis block hash.
=> fix genesis timestamp

ethereum/pruning_trie.py, ethereum/snapshot.py
Add a new module `snapshot.py` so we can create snapshot and load it back later.
Snapshot is saved in a JSON format file, including three main components:
* chain difficulty
* World state (list of accounts)
* Recent blocks (default to 1024)
Snapshot can be used to prune state data regularly (and manually) and boost py nodes startup time (by starting from a snapshot).
=> State snapshot module

ethereum/chain.py, ethereum/consensus_strategy.py, ethereum/tests/test_chain.py, requirements.txt
This PR provides Python3 support for `chain.py`, `consensus_strategy.py`, and `test_chain.py`. I did this because the Casper contract is written in Viper, which can only be compiled using Python3. Therefore to add Casper support, it seemed like we should also have Python3 support.
I tested this and it passed in `Python 3.6.1` and `Python 2.7.10`.
- Fix a bunch of Python3 bytes errors in `chain.py` & `test_chain.py`
- Remove relative imports in `consensus_strategy.py`
- Add [the package `future`](http://python-future.org/) to fix `Memory Error` when moving from `xrange()` to -> `range()` in Python2.7. I hate adding a new dependency but I wasn't able to find a cleaner solution.
=> Add python3 support for test_chain.py

ethereum/tester2.py
Fixes two small bugs I came across while porting `simple_casper_tester.py` to `tester2`.
The issue with revert was caused if you don't `commit()` before creating your snapshot, you will end up getting `Cannot return to this snapshot` when calling revert(). This is because `journal_length != 0`
=> Fix tester2 broken revert & undefined variable

ethereum/parse_genesis_declaration.py
It was wrongly encoding difficulty/gasLimit as hex, but the other
functions there (e.g. block_from_genesis_declaration) parse those as ints.
=> Fix parse_genesis_declaration.mk_genesis_data()

.gitignore
Add '.env' file to .gitignore for personal [autoenv](https://github.com/kennethreitz/autoenv) settings
[autoenv](https://github.com/kennethreitz/autoenv) can auto-activating virtualenvs
If a directory contains a .env file, it will automatically be executed when you cd into it.
=> add .env to gitignore for personal pyenv, autoenv settings

ethereum/__init__.py, ethereum/abi.py, ethereum/experimental/pruning_trie.py, ethereum/tests/test_contracts.py, ethereum/tests/todo/test_serialization.py, ethereum/tests/todo/test_solidity.py, ethereum/trie.py, ethereum/utils.py, tools/fixture_to_example.py
- Updated docstrings using Triple-single-quotes to Triple-double-quotes according to [PEP 257 -- Docstring Conventions](https://www.python.org/dev/peps/pep-0257/)
- Updated to use Triple-double-quotes when assign contract codes
=> Fixed contracts and docstrings to triple-double-quotes

.travis.yml, Makefile
The idea is to run just the tests that are currently passing, and add
new ones as they're fixed.
=> New Makefile rule to run just a minimal set of tests

ethereum/config.py, ethereum/genesis_helpers.py, ethereum/pow/chain.py
```from ethereum.tools import tester as tester
from ethereum.abi import ContractTranslator
from ethereum.tools.tester import ABIContract
from ethereum import utils as u
from ethereum.config import config_metropolis, Env
config_metropolis['BLOCK_GAS_LIMIT'] = 2**60
chain = tester.Chain(env=Env(config=config_metropolis))
chain.contract('file.se', language='serpent', startgas=long(6 * 10**6))
chain.mine()
```
Now works with this system, resolves #769
=> add BLOCK_GAS_LIMIT

ethereum/slogging.py, ethereum/tests/test_tester.py, ethereum/tools/tester.py, ethereum/transactions.py, requirements.txt
This PR includes changes which I made while developing Casper, which are not core to Casper itself but instead changes to `pyethereum` more generally.
- Add `change_head` which allows you to pick a new head to build on within your chain. This is super useful for testing forking logic
- Add `State`: This class is a simplified version of `Chain` which doesn't have any block logic.
- Add `call`: Tester will now detect that a transaction can be a call and should therefore not be actually submitted to the block and instead just allow the value to be returned.
Set `logger.propagate` to False, unless explicitly specified in the config string. If no config string is given, then we use the defaults.
I made this change because I felt like the config string might have been broken, and this seemed to …
=> Update tester, slogging, & transactions

ethereum/utils.py, requirements.txt
This is a continuation of https://github.com/ethereum/pyethereum/pull/713 which is meant to address https://github.com/ethereum/pyethereum/issues/708
I accidentally deleted the original fork.
@ofek
=> Switched to coincurve

ethereum/tools/tester.py
To prevent from the error when `self.last_sender` is `None` already.
The following lines are the error messages:
```bash
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../.pyenv/versions/py3.6.0eth/lib/python3.6/site-packages/ethereum-2.0.4-py3.6.egg/ethereum/tools/tester.py:160: in direct_tx
if privtoaddr(self.last_sender) != transaction.sender:
../../../.pyenv/versions/py3.6.0eth/lib/python3.6/site-packages/ethereum-2.0.4-py3.6.egg/ethereum/utils.py:188: in privtoaddr
k = normalize_key(k)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ $
key = None
def normalize_key(key):
if …
```
=> Add a check in tester.direct_tx

requirements.txt
pycryptodome was in at https://github.com/ethereum/pyethereum/commit/66d88fe8069490e7ec53c1acf157ed0ba5ce83c0
but was regressed in https://github.com/ethereum/pyethereum/commit/85efc8688a3adb45cf9e74fa17022ca4df3ad16a
=> add pycryptodome to requirements.txt again

ethereum/utils.py
There was an improper rebase in #777. This restores that fix.
=> fix var name in utils.ecsign

ethereum/utils.py
I'm not sure why someone thought that `bytes` was the correct value here, but `is_string('hello')` returns false in Python 3 with the old code.
=> Fixes bug in `is_string`.

dev_requirements.txt
Hi, this is something we stumbled upon when trying to run the testsuite from within ``pyethereum`` to compare the stack traces with ``ethereumjs`` results. Thought I make a short pull request.
=> Added py-ecc (ethereum/py_pairing) to dev_requirements.txt
